# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: adrianacmy
# email: adrianamullaney@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "venusgrape.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  adrianacmy
permalink: pretty
disqus_shortname: adrianawritescode-com

highlighter: rouge
# 
# Jekyll 3 now only supports Kramdown for Markdown
# kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  # input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  # syntax_highlighter: rouge
  # syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    # css_class: 'highlight'

fenced_code_blocks: true
# Build settings
markdown: kramdown
# theme: minima
# gems:
#   - jekyll-feed
exclude: ['Gemfile', 'Gemfile.lock', 'README.md' ]

